export const CategoryData = [
  { name: "Electronics" },
  { name: "Mobiles" },
  { name: "Computers" },
  { name: "Fashion" },
  { name: "Home & Kitchen" },
  { name: "Sports" },
  { name: "Books" },
  { name: "Groceries" },
  { name: "Toys" },
  { name: "Beauty" },
];

export const ProductStatusData = [
  { status: "active" },
  { status: "inactive" },
  { status: "archived" },
  { status: "out-of-stock" },
  { status: "discontinued" },
  { status: "pending" },
  { status: "draft" },
  { status: "hidden" },
  { status: "deleted" },
  { status: "active" },
];

const now = Date.now();
export const ProductsData = [
  {
    name: "iPhone 14 Pro Max",
    price: 1299,
    stock: 25,
    category: "Mobiles",
    description:
      "Apple iPhone 14 Pro Max with A16 Bionic chip and Dynamic Island.",
    // images: ["https://example.com/images/iphone14pro.jpg"],
    vendor: "Apple Store",
    status: "active",
  },
  {
    name: "Samsung Galaxy S23 Ultra",
    price: 1199,
    stock: 40,
    category: "Mobiles",
    description: "Samsung flagship with 200MP camera and Snapdragon 8 Gen 2.",
    // images: ["https://example.com/images/galaxyS23.jpg"],
    vendor: "Samsung Shop",
    status: "out-of-stock",
  },
  {
    name: "Dell XPS 15",
    price: 1899,
    stock: 15,
    category: "Computers",
    description: "Powerful 15-inch laptop with Intel i7 and OLED display.",
    // images: ["https://example.com/images/dellxps15.jpg"],
    vendor: "Dell Official",
    status: "active",
  },
  {
    name: "Nike Air Max 270",
    price: 150,
    stock: 80,
    category: "Fashion",
    description: "Comfortable lifestyle sneakers with Air cushioning.",
    // images: ["https://example.com/images/nike270.jpg"],
    vendor: "Nike Store",
    status: "pending",
  },
  {
    name: "Levi’s 501 Original Jeans",
    price: 89,
    stock: 120,
    category: "Fashion",
    description: "Classic fit denim jeans with a timeless look.",
    // images: ["https://example.com/images/levis501.jpg"],
    vendor: "Levi’s",
    status: "draft",
  },
  {
    name: "Sony WH-1000XM5",
    price: 399,
    stock: 50,
    category: "Electronics",
    description: "Industry-leading noise-canceling wireless headphones.",
    // images: ["https://example.com/images/sonyxm5.jpg"],
    vendor: "Sony Store",
    status: "active",
  },
  {
    name: "LG 55-inch OLED TV",
    price: 1299,
    stock: 10,
    category: "Electronics",
    description: "4K OLED smart TV with HDR and Dolby Vision.",
    // images: ["https://example.com/images/lg55oled.jpg"],
    vendor: "LG Electronics",
    status: "archived",
  },
  {
    name: "KitchenAid Stand Mixer",
    price: 349,
    stock: 30,
    category: "Home & Kitchen",
    description: "Versatile mixer for baking and cooking needs.",
    // images: ["https://example.com/images/kitchenaid.jpg"],
    vendor: "KitchenAid",
    status: "active",
  },
  {
    name: "Prestige Pressure Cooker",
    price: 79,
    stock: 60,
    category: "Home & Kitchen",
    description: "Durable stainless steel pressure cooker.",
    // images: ["https://example.com/images/prestige_cooker.jpg"],
    vendor: "Prestige",
    status: "inactive",
  },
  {
    name: "Yonex Badminton Racket",
    price: 199,
    stock: 25,
    category: "Sports",
    description: "Professional-grade lightweight racket for tournaments.",
    // images: ["https://example.com/images/yonex.jpg"],
    vendor: "Yonex",
    status: "active",
  },
  {
    name: "Spalding Basketball",
    price: 49,
    stock: 70,
    category: "Sports",
    description: "Official NBA basketball for indoor and outdoor use.",
    // images: ["https://example.com/images/spalding.jpg"],
    vendor: "Spalding",
    status: "deleted",
  },
  {
    name: "Harry Potter Box Set",
    price: 120,
    stock: 40,
    category: "Books",
    description: "Complete collection of Harry Potter novels.",
    // images: ["https://example.com/images/harrypotter.jpg"],
    vendor: "Bloomsbury",
    status: "active",
  },
  {
    name: "Atomic Habits",
    price: 18,
    stock: 150,
    category: "Books",
    description: "James Clear’s bestselling book on building good habits.",
    // images: ["https://example.com/images/atomichabits.jpg"],
    vendor: "Penguin Random House",
    status: "archived",
  },
  {
    name: "Nestle Everyday Milk Powder",
    price: 8,
    stock: 200,
    category: "Groceries",
    description: "Instant milk powder for tea and coffee.",
    // images: ["https://example.com/images/nestlemilk.jpg"],
    vendor: "Nestle",
    status: "active",
  },
  {
    name: "Tata Salt",
    price: 2,
    stock: 500,
    category: "Groceries",
    description: "Iodized salt trusted by millions.",
    // images: ["https://example.com/images/tatasalt.jpg"],
    vendor: "Tata",
    status: "draft",
  },
  {
    name: "Hot Wheels Car Set",
    price: 25,
    stock: 300,
    category: "Toys",
    description: "Pack of 10 miniature die-cast cars.",
    // images: ["https://example.com/images/hotwheels.jpg"],
    vendor: "Mattel",
    status: "pending",
  },
  {
    name: "Lego Star Wars Millennium Falcon",
    price: 799,
    stock: 20,
    category: "Toys",
    description: "Massive Lego build set of the iconic spaceship.",
    // images: ["https://example.com/images/lego_falcon.jpg"],
    vendor: "Lego",
    status: "active",
  },
  {
    name: "Lakme Lipstick Set",
    price: 35,
    stock: 100,
    category: "Beauty",
    description: "Set of 5 matte-finish lipsticks.",
    // images: ["https://example.com/images/lakme.jpg"],
    vendor: "Lakme",
    status: "hidden",
  },
  {
    name: "Maybelline Mascara",
    price: 12,
    stock: 200,
    category: "Beauty",
    description: "Volumizing waterproof mascara.",
    // images: ["https://example.com/images/maybelline_mascara.jpg"],
    vendor: "Maybelline",
    status: "active",
  },
  {
    name: "Dell Inspiron 15 Laptop",
    price: 55000,
    stock: 18,
    category: "Computers",
    description: "15.6-inch laptop with Intel i5, 8GB RAM, 512GB SSD.",
    // images: ["https://picsum.photos/200?random=21"],
    vendor: "Dell India",
    status: "active",
  },
  {
    name: "Sony Bravia 55-inch 4K TV",
    price: 72000,
    stock: 10,
    category: "Electronics",
    description: "Ultra HD smart LED TV with HDR and voice control.",
    // images: ["https://picsum.photos/200?random=22"],
    vendor: "Sony",
    status: "inactive",
  },
  {
    name: "Apple Watch SE",
    price: 28000,
    stock: 20,
    category: "Fashion",
    description: "Smartwatch with fitness tracking and notifications.",
    // images: ["https://picsum.photos/200?random=23"],
    vendor: "Apple",
    status: "pending",
  },
  {
    name: "Adidas Running Shoes",
    price: 3500,
    stock: 65,
    category: "Sports",
    description: "Lightweight running shoes for daily fitness.",
    // images: ["https://picsum.photos/200?random=24"],
    vendor: "Adidas",
    status: "active",
  },
  {
    name: "Levi’s Denim Jacket",
    price: 4200,
    stock: 33,
    category: "Fashion",
    description: "Classic blue denim jacket for casual wear.",
    // images: ["https://picsum.photos/200?random=25"],
    vendor: "Levi's",
    status: "draft",
  },
  {
    name: "Prestige Mixer Grinder",
    price: 2800,
    stock: 45,
    category: "Home & Kitchen",
    description: "3-jar mixer grinder for kitchen needs.",
    // images: ["https://picsum.photos/200?random=26"],
    vendor: "Prestige",
    status: "active",
  },
  {
    name: "Casio Scientific Calculator",
    price: 950,
    stock: 200,
    category: "Electronics",
    description: "FX-991EX scientific calculator for students.",
    // images: ["https://picsum.photos/200?random=27"],
    vendor: "Casio",
    status: "archived",
  },
  {
    name: "Asus ROG Gaming Laptop",
    price: 115000,
    stock: 7,
    category: "Computers",
    description: "High performance gaming laptop with RTX 4060.",
    // images: ["https://picsum.photos/200?random=28"],
    vendor: "Asus",
    status: "active",
  },
  {
    name: "Amazon Echo Dot 5th Gen",
    price: 4500,
    stock: 80,
    category: "Electronics",
    description: "Smart speaker with Alexa voice assistant.",
    // images: ["https://picsum.photos/200?random=29"],
    vendor: "Amazon",
    status: "hidden",
  },
  {
    name: "Philips Hair Dryer",
    price: 1700,
    stock: 100,
    category: "Beauty",
    description: "1200W hair dryer with thermoprotect technology.",
    // images: ["https://picsum.photos/200?random=30"],
    vendor: "Philips",
    status: "active",
  },
  {
    name: "Nestle Everyday Dairy Whitener",
    price: 340,
    stock: 300,
    category: "Groceries",
    description: "Milk powder whitener for tea and coffee.",
    // images: ["https://picsum.photos/200?random=31"],
    vendor: "Nestle",
    status: "active",
  },
  {
    name: "Monopoly Classic Board Game",
    price: 1100,
    stock: 90,
    category: "Toys",
    description: "Classic property trading board game for family fun.",
    // images: ["https://picsum.photos/200?random=32"],
    vendor: "Hasbro",
    status: "inactive",
  },
  {
    name: "Samsung Galaxy Tab A9",
    price: 18000,
    stock: 25,
    category: "Electronics",
    description: "Affordable Android tablet with large display.",
    // images: ["https://picsum.photos/200?random=33"],
    vendor: "Samsung",
    status: "active",
  },
  {
    name: "Nike Sports T-shirt",
    price: 1200,
    stock: 70,
    category: "Fashion",
    description: "Breathable sports t-shirt for workouts.",
    // images: ["https://picsum.photos/200?random=34"],
    vendor: "Nike",
    status: "draft",
  },
  {
    name: "Anchor 4-way Extension Board",
    price: 650,
    stock: 120,
    category: "Electronics",
    description: "Surge protected extension board with 4 sockets.",
    // images: ["https://picsum.photos/200?random=35"],
    vendor: "Anchor",
    status: "active",
  },
  {
    name: "Himalaya Face Wash",
    price: 120,
    stock: 500,
    category: "Beauty",
    description: "Neem face wash for clear skin.",
    // images: ["https://picsum.photos/200?random=36"],
    vendor: "Himalaya",
    status: "pending",
  },
  {
    name: "Sony WH-1000XM4 Headphones",
    price: 28000,
    stock: 14,
    category: "Electronics",
    description: "Noise cancelling wireless over-ear headphones.",
    // images: ["https://picsum.photos/200?random=37"],
    vendor: "Sony",
    status: "active",
  },
  {
    name: "Butterfly Gas Stove",
    price: 3500,
    stock: 60,
    category: "Home & Kitchen",
    description: "2-burner gas stove with toughened glass top.",
    // images: ["https://picsum.photos/200?random=38"],
    vendor: "Butterfly",
    status: "discontinued",
  },
  {
    name: "Campus School Bag",
    price: 890,
    stock: 140,
    category: "Fashion",
    description: "Durable backpack for school and college students.",
    // images: ["https://picsum.photos/200?random=39"],
    vendor: "Campus",
    status: "active",
  },
  {
    name: "Tata Salt Lite",
    price: 25,
    stock: 800,
    category: "Groceries",
    description: "Low-sodium iodized salt for healthy lifestyle.",
    // images: ["https://picsum.photos/200?random=40"],
    vendor: "Tata",
    status: "active",
  },
  {
    name: "LG Washing Machine 7kg",
    price: 28000,
    stock: 12,
    category: "Home & Kitchen",
    description: "Fully automatic front load washing machine.",
    // images: ["https://picsum.photos/200?random=41"],
    vendor: "LG",
    status: "active",
  },
  {
    name: "Whirlpool Refrigerator 260L",
    price: 32000,
    stock: 8,
    category: "Home & Kitchen",
    description: "Double door refrigerator with frost free cooling.",
    // images: ["https://picsum.photos/200?random=42"],
    vendor: "Whirlpool",
    status: "inactive",
  },
  {
    name: "Colgate Toothpaste Value Pack",
    price: 180,
    stock: 600,
    category: "Groceries",
    description: "Anti-cavity toothpaste pack of 4.",
    // images: ["https://picsum.photos/200?random=43"],
    vendor: "Colgate",
    status: "active",
  },
  {
    name: "HarperCollins Book - Atomic Habits",
    price: 480,
    stock: 100,
    category: "Books",
    description: "Bestselling book by James Clear on building habits.",
    // images: ["https://picsum.photos/200?random=44"],
    vendor: "HarperCollins",
    status: "active",
  },
  {
    name: "Amul Butter 500g",
    price: 280,
    stock: 350,
    category: "Groceries",
    description: "Pure and fresh butter by Amul.",
    // images: ["https://picsum.photos/200?random=45"],
    vendor: "Amul",
    status: "archived",
  },
  {
    name: "OnePlus Buds Pro 2",
    price: 11500,
    stock: 32,
    category: "Electronics",
    description: "Wireless earbuds with adaptive noise cancellation.",
    // images: ["https://picsum.photos/200?random=46"],
    vendor: "OnePlus",
    status: "active",
  },
  {
    name: "Pigeon Pressure Cooker 5L",
    price: 2100,
    stock: 70,
    category: "Home & Kitchen",
    description: "5 litre aluminium pressure cooker for daily use.",
    // images: ["https://picsum.photos/200?random=47"],
    vendor: "Pigeon",
    status: "hidden",
  },
  {
    name: "Funskool Remote Car",
    price: 1450,
    stock: 85,
    category: "Toys",
    description: "Battery operated remote control racing car.",
    // images: ["https://picsum.photos/200?random=48"],
    vendor: "Funskool",
    status: "active",
  },
  {
    name: "Godrej Air Freshener Spray",
    price: 170,
    stock: 210,
    category: "Home & Kitchen",
    description: "Air freshener with long lasting fragrance.",
    // images: ["https://picsum.photos/200?random=49"],
    vendor: "Godrej",
    status: "draft",
  },
  {
    name: "Pepsi 2L Bottle",
    price: 110,
    stock: 400,
    category: "Groceries",
    description: "Carbonated soft drink, 2L PET bottle.",
    // images: ["https://picsum.photos/200?random=50"],
    vendor: "PepsiCo",
    status: "active",
  },
].map((data, index) => ({
  ...data,
  images: [`https://picsum.photos/id/${index}/200/300`],
  createdAt: new Date(now - (index + 1) * 1000),
}));
